### ISSUE TITLE
MySQL db won't spin yp

### ISSUE THREAD

**Issue by hmook** [koalatiapp/hosting#3] opened 2023-03-26 18:51 UTC
Hi when installing the hosted version on local machine (docker) everything starts fine except the koala_database container keeps starting and exiting again giving this log:

`2023-03-26 18:44:04+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.32-1.el8 started.
2023-03-26 18:44:06+00:00 [Note] (Entrypointl: Switching to dedicated user 'mysql'
2023-03-26 18:44:07+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.32-1.18 started.
"/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
2023-03-26718:44:07.5945322 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
2023-03-26718:44:07.601158Z 0 [System] [MY-010116] [Server] /us/sbin/mysqld (mysqld 8.0.32) starting as process 1
2023-03-26T18:44:07.719277Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2023-03-26T18:44:08.105726Z 1 [ERROR] [MY-012960] [InnoDB] Cannot create redo log files because data files are corrupt or the database was not shut down cleanly after creating the data files.
2023-03-26718:44:08.354601Z 1 [ERROR] [MY-010334] [Server] Failed to initialize DD Storage Engine
2023-03-26718:44:08.354808Z 0 (ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2023-03-26718:44:08.354840Z 0 [ERROR] [MY-010119] [Server] Aborting
2023-03-26718:44:08.355587Z 0 [System] [MY-010910] [Server] /us/sbin/mysqld: Shutdown complete (mysqld 8.0.32) MySQL Community Server - GPL.
2023-03-26 18:46:37+00:00 [Note] [Entrypointl: Entrypoint script for MySOL Server 8.0.32-1.18 started.
2023-03-26 18:46:37+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-03-26 18:46:37+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.32-1.el8 started.
"/var/lib/mysql/mysql.sock' -> /var/run/mysqld/mysqld.sock'
2023-03-26718:46:38.085327Z 0 [Warning] [MY-011068] [Server] The syntax --skip-host-cache' is deprecated and will be removed in a future release. Please Use SET GLOBAL host_cache_size=0 instead.
2023-03-26718:46:38.212328Z 0 [System] [MY-010116] [Server] /us/sbin/mysqld (mysqld 8.0.32) starting as process 1
2023-03-26T18:46:38.436085Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2023-03-26718:46:38.540144Z 1 [ERROR] [MY-012960] [InnoDB] Cannot create redo log files because data files are corrupt or the database was not shut down cleanly after creating the data files.
2023-03-26718:46:38.994439Z 1 [ERROR] [MY-010334] [Server] Failed to initialize DD Storage Engine
2023-03-26718:46:38.994753Z 0 (ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2023-03-26T18:46:38.994776Z 0 [ERROR] [MY-010119] [Server] Aborting
2023-03-2618:46:38.995476Z 0 [System] [MY-010910] [Server\ /us/sbin/mysqld: Shutdown complete (mysqld 8.0.32) MySQL Community Server - GPL.`

Is this a know issue and is this been resolved before?

**Comment by EmilePerron** [comment] 2023-03-27 02:46
Hi @hmook!

This is not an issue that I have seen or that had been reported before, no.

At a quick glance, it looks like it may be related to the MySQL image itself more than Koalati’s usage of it.

Perhaps you could try to spin up just the MySQL Docker image on its own, without the other containers and configs, just to see if you get the same issue?

**Comment by hmook** [comment] 2023-03-27 17:38
SQL container it selfs won't spin up on its on. Tried to repull from git and got a new error when performing 
`'docker-compose up'`

```
WARNING: Python-dotenv could not parse statement starting at line 2
Creating koalati_adminer_1  ... done
Creating koalati_redis_1    ... done
Creating koalati_database_1 ... done
Creating koalati_tools-service_1 ... done

ERROR: for php  Container "3a0dd480adbd" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

Can't see any abonormalities in the compose file nor in the env file.
Any clue?

**Comment by EmilePerron** [comment] 2023-03-28 12:03
This is also the first time I see this issue.

From what I’ve read online, it seems like it could be related to issues in the .env file. 

I know you checked already, but I suspect it may be caused by special characters that aren’t escaped correctly in the .env values generated automatically by the setup script.

Could you take a look at those generated values and see if replacing some special characters with regular characters fixes the issue?

**Comment by hmook** [comment] 2023-03-28 18:29
Hi @EmilePerron thanks again for the response. Got some steps further. Containers are starting/ installing seems to work but the 'koalati_php_1' container keeps restarting with a set of twig errors:

`setfacl: var/cache/prod/twig/ff: Not supported
setfacl: var/cache/prod/twig/ff/fffcafca64242bc460e907cecb20e687.php: Not supported
setfacl: var/cache/prod/url_generating_routes.php: Not supported
setfacl: var/cache/prod/url_generating_routes.php.meta: Not supported
setfacl: var/cache/prod/url_matching_routes.php: Not supported
setfacl: var/cache/prod/url_matching_routes.php.meta: Not supported
setfacl: var/cache/prod/validation.php: Not supported
setfacl: var/cache/prod/webpack_encore.cache.php: Not supported
setfacl: var/log: Not supported
`

And after that:

`koalati_php_1 exited with code 1`

have change some port settings and volume mapping to match my synology docker structure as well this made the container installation work. But still no usable app unfortunately.

Hope you can help.

**Comment by EmilePerron** [comment] 2023-03-29 12:21
Hi @hmook,

It seems like your OS or environment does not support `setfacl`, which Koalati relies on to manage permissions inside its Docker entrypoint script. See here: https://github.com/koalatiapp/app/blob/d3e4afd0e66f5bef983baeafced83b9c88912963/docker/php/docker-entrypoint.sh#L63-L71

I don't know much about your environment, and I know fairly little about `acl` as well so I'm not sure how easy or difficult a fix it would be to get it set up & working on your environment. I found this comment thread in an issue of the Docker template we use, which may be relevant to your situation: https://github.com/dunglas/symfony-docker/issues/67#issuecomment-663828901

Alternatively, you could try and change the Entrypoint script for this image so that it handles permissions in a different way (without using `setfacl`), although this may also require quite a bit of effort.

Hope that helps!

**Comment by EmilePerron** [comment] 2023-04-07 11:34
Hi @hmook, 

I'll close this issue - if there's anything else I can do to help, feel free to comment again here or to create a new issue.

Cheers!

**Closed as completed by EmilePerron** 2023-04-07 11:34 UTC
